### ISSUE TITLE
Problemas de atalhos e nomes nos materiais complementares 

### ISSUE THREAD

**Issue by yuukiozk** [senaidev-ead/oficina-de-recuperacao-senai2021#1]
Tutores, notei um erro no site do materiais complementares referente a atalhos e nomenclaturas dentro das uc´s 

1.  Na UC10, na "header", não há o atalho para o UC11. No caso o aluno deve voltar ate a página inicial e ir para o uc desejado (conforme a foto anexada.
![Erro uc10](https://user-images.githubusercontent.com/74884888/140746287-e000e75d-8a54-4e55-bec3-e7c939702c98.png)

2. Já no UC11, na parte de cima, ao lado do "voltar para o menu principal", está escrito "10 - Criação e Manipulação de Banco de Dados"

![Erro uc11](https://user-images.githubusercontent.com/74884888/140746477-fb05c82f-3f89-4251-8bc2-96efbff7861b.png)

**Comment by FilosoDev** [comment]
Joshua, quer fazer um pull request e consertar?

Faz e a gente faz o code review.

**Comment by yuukiozk** [comment]
@FilosoDev Feito! [https://github.com/senaidev-ead/materiais-complementares-2021/pull/2]

**Comment by FilosoDev** [comment]
Não querendo abusar, mas se você quiser praticar, as demais páginas estão sem a UC 11 no menu. : )

**Comment by yuukiozk** [comment]
@FilosoDev [Aqui!](https://github.com/senaidev-ead/materiais-complementares-2021/pull/3)

**Comment by yuukiozk** [comment]
Tutor @FilosoDev, uma duvida, seria interessante se fizesse um fórum para todos os estudantes dentro do materiais complementares ? 
Como não temos tanto contatos com outros alunos/unidades, seria interessante de "unir".

**Comment by FilosoDev** [comment]
Joshua, o fórum teria que rodar uma linguagem dinâmica. No GitHub Pages não tem isso.  Somente páginas estáticas.
