### ISSUE TITLE
Sugestão de uma nova lacuna

### ISSUE THREAD

**Issue by yuukiozk** [senaidev-ead/oficina-de-recuperacao-senai2021#4]
Tutores, uma duvida

Desde o começo, os plantões de duvidas ao vivo auxiliam e muito o aprendizado e o conhecimento aprofundado nas uc´s.
Porem, não tão sendo tão divulgados ou temos as datas/horas dos plantões.

Teria como fazer uma página dentro dos materiais complementares colocando o link, data/hora e o professor para saber se haverá ou não os plantões?

Fico no aguardo!

**Comment by yuukiozk** [comment]
Fiz uma base no Pull request [Aqui](https://github.com/senaidev-ead/materiais-complementares-2021/pull/5)!

**Comment by FilosoDev** [comment]
Joshua, até seria uma boa ideia. Mas o problema é que o modelo dos plantões mudou.

Agora será nos moldes de "aula temática".

Precisaria saber se vai haver links fixos para serem postados.
